.template:
  image: gradle:6.8.3-jdk15-openj9
  script:
    - echo "I am from included file"

  before_script:
    - export GRADLE_USER_HOME=cache/.gradle

  cache:
    paths:
      - $GRADLE_USER_HOME/caches/
      - $GRADLE_USER_HOME/wrapper/
      - $GRADLE_USER_HOME/build-cache/

